name: Build-AddIn-Assembly
runs:
  using: "composite"
  steps:
    # Checkout the code.
    - uses: actions/checkout@v3
    # Add msbuild to the path so we can execute it.
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    # Restore the solution depencies (NuGet restore).
    - name: Restore dependencies
      run: msbuild -t:restore
    # Build the solution (without installer).
    - name: Build assembly
      shell: cmd
      run: |
        msbuild PowerDesigner_OData_AddIn.sln -property:Configuration=Release