name: build-addin

on:
  workflow_dispatch:
    inputs:
      build_msi:
        description: 'Build Installer'
        required: false
        default: false
        type: boolean

runs:
  using: "composite"
  steps:

    # Add msbuild to the path so we can execute it.
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    # Restore the solution depencies (NuGet restore).
    - name: Restore dependencies
      shell: cmd
      run: msbuild -t:restore
    # Install GitVersion
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.15
      with:
        versionSpec: '5.5.x'
    # Update the version numbers.
    - name: Determine Version
      id: gitversion # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v0.9.15
      with:
        updateAssemblyInfo: true
    # Build the solution (without installer).
    - name: Build assembly
      shell: cmd
      run: |
        msbuild PowerDesigner_OData_AddIn.sln -property:Configuration=Release

    # The steps below are only executed when the build_msi input is set to true.

    # Prepare the build-container to be able to build visual studio setup projects.
    - name: Prepare installer build
      shell: cmd
      run: |
        DisableOutOfProcBuild.exe
      working-directory: ${{env.VS_COMMON_IDE_PATH}}/CommonExtensions/Microsoft/VSI/DisableOutOfProcBuild
      if: ${{ inputs.build_msi }}
    # Update ProductVersion for Setup Project.
    - name: Update ProductVersion for Installer
      env:
        PRODUCT_VERSION: ${{ steps.gitversion.outputs.fullSemVer }}
      shell: pwsh
      run: |
        $vdprojFile = "PowerDesigner_OData_AddIn_Setup/PowerDesigner_OData_AddIn_Setup.vdproj"
        $vdprojProductVersion = $env:PRODUCT_VERSION
        (Get-Content $vdprojFile) -replace '\"ProductVersion\" = \"8\:[0-9]+(\.([0-9]+)){1,3}\"', "ProductVersion" = "8:' + $vdprojProductVersion + '"' } | Set-Content $vdprojFile
      if: ${{ inputs.build_msi }}
    # Build the setup project using devenv.
    - name: Build installer
      shell: cmd
      run: |
        "%VS_COMMON_IDE_PATH%\devenv.com" "PowerDesigner_OData_AddIn.sln" /Build Release /project PowerDesigner_OData_AddIn_Setup
      if: ${{ inputs.build_msi }}
    # Publish the installer as a build artifact.
    - name: Publish installer
      uses: actions/upload-artifact@v3
      with:
        name: PD_OData_AddIn_${{ steps.gitversion.outputs.fullSemVer }}
        path: PowerDesigner_OData_AddIn_Setup/Release/PowerDesigner_OData_AddIn_Setup.msi
      if: ${{ inputs.build_msi }}