name: Build-AddIn

on: [push]

jobs:
  build:

    runs-on: windows-2019 # Use Windows 2019 image since this one has the .NET Framework 4.7.2 pre-installed.

    env:
      DEVENV_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\devenv.com

    steps:	
    - uses: actions/checkout@v3
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Restore dependencies
      run: msbuild -t:restore
    - name: Build assembly
      run: msbuild PowerDesigner_OData_AddIn.sln -property:Configuration=Release
    - name: Build installer
      shell: cmd
      run: |
        "%DEVENV_PATH%" "PowerDesigner_OData_AddIn.sln" /Build Release /project PowerDesigner_OData_AddIn_Setup