name: Build-AddIn

on: [push]

jobs:
  build:

    runs-on: windows-2019 # Use Windows 2019 image since this one has the .NET Framework 4.7.2 pre-installed.

    steps:
    - uses: actions/checkout@v3
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Restore dependencies
      run: msbuild -t:restore
    - name: Build
      run: msbuild PowerDesigner_OData_AddIn.sln -verbosity:diag -property:Configuration=Debug
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal