name: feature

on:
  push:
    branches:
      - feature/*

jobs:
  build:

    # Use Windows 2019 image since this one has the .NET Framework 4.7.2 pre-installed.
    # https://github.com/actions/runner-images/blob/main/images/win/Windows2019-Readme.md
    runs-on: windows-2019

    steps:
    # Checkout the code.
    - uses: actions/checkout@v3
      # For the GitVersion to execute successfully, we need the checkout to fetch all gistory for all tags and branches (with fetch-depth: 0).
      with:
        fetch-depth: 0
    # Use the build-assembly action.
    - uses: ./.github/actions/build-assembly
