name: main

on:
  push:
    branches:
      - main

jobs:
  build:

    # Use Windows 2019 image since this one has the .NET Framework 4.7.2 pre-installed.
    # https://github.com/actions/runner-images/blob/main/images/win/Windows2019-Readme.md
    runs-on: windows-2019

    env:
      # Environment variable which points to the VS 2019 IDE folder.
      VS_COMMON_IDE_PATH: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/IDE

    steps:
    - uses: actions/checkout@v3
    # Use the build-assembly action.
    - uses: ./.github/actions/build-assembly
    # Prepare the build-container to be able to build visual studio setup projects.
    - name: Prepare installer build
      shell: cmd
      run: |
        DisableOutOfProcBuild.exe
      working-directory: ${{env.VS_COMMON_IDE_PATH}}/CommonExtensions/Microsoft/VSI/DisableOutOfProcBuild
    # Build the setup project using devenv.
    - name: Build installer
      shell: cmd
      run: |
        "%VS_COMMON_IDE_PATH%\devenv.com" "PowerDesigner_OData_AddIn.sln" /Build Release /project PowerDesigner_OData_AddIn_Setup
    # Publish the installer as a build artifact.
    - name: Publish installer
      uses: actions/upload-artifact@v3
      with:
        name: PD_OData_AddIn_${{ github.run_number }}_${{ github.run_attempt }}
        path: PowerDesigner_OData_AddIn_Setup/Release/PowerDesigner_OData_AddIn_Setup.msi
